### ISSUE TITLE
Undefined Reference to 'get_ptr_temp_but_2'

### ISSUE THREAD

**Issue by stupdude2** [Yuukari/BipTaskTemplate#1]
When I try to compile this project, I get the following screen.

> Assembly...arm-none-eabi-ld: BipTaskTemplate-master.elf: error: PHDR segment not covered by LOAD segment
> arm-none-eabi-ld: app.o: in function `screen_job':
> app.c:(.text.screen_job+0x2): undefined reference to `get_ptr_temp_buf_2'
> arm-none-eabi-ld: app.o: in function `key_press_screen':
> app.c:(.text.key_press_screen+0x2): undefined reference to `get_ptr_temp_buf_2'
> arm-none-eabi-ld: app.o: in function `draw_switch_screen':
> app.c:(.text.draw_switch_screen+0x2): undefined reference to `get_ptr_temp_buf_2'
> arm-none-eabi-ld: app.o: in function `show_screen':
> app.c:(.text.show_screen+0x4): undefined reference to `get_ptr_temp_buf_2'
> arm-none-eabi-ld: app.c:(.text.show_screen+0x18): undefined reference to `get_var_menu_overlay'
> arm-none-eabi-ld: app.c:(.text.show_screen+0x5e): undefined reference to `pvPortMalloc'
> arm-none-eabi-ld: app.o: in function `draw_buttons_screen':
> app.c:(.text.draw_buttons_screen+0x2): undefined reference to `get_ptr_temp_buf_2'
> arm-none-eabi-ld: app.o: in function `draw_random_screen':
> app.c:(.text.draw_random_screen+0x4): undefined reference to `get_ptr_temp_buf_2'
> arm-none-eabi-ld: app.o: in function `dispatch_screen':
> app.c:(.text.dispatch_screen+0x4): undefined reference to `get_ptr_temp_buf_2'
> ERROR
> Press any key to continue . . .

![image](https://user-images.githubusercontent.com/18221385/114093147-61dc5e80-9880-11eb-8ea1-5a6f607e3250.png)

**Comment by yuukari** [comment]
Hello! 

I had the same problem when I wanted use latest compiler version. As I can see, you using GNU ARM toolchain with version "10 2020-q4-major". Try to remove this version and install release "8-2019-q3-update" from here: https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

**Comment by stupdude2** [comment]
I uninstalled the newer GNU ARM Toolchain and installed 8- 2019-q3-update and it still was giving me the same errors.

I found this file https://myamazfit.ru/attachments/dnd-zip.30903/ and it compiled for me.

![image](https://user-images.githubusercontent.com/18221385/114186385-63536880-990c-11eb-9194-3f67edd6b744.png)
